//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AxWorkerInfo", Namespace="http://schemas.datacontract.org/2004/07/PMS.Models")]
    public partial class AxWorkerInfo : object
    {
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        private string BirthDateStrField;
        
        private string DepField;
        
        private string EmailField;
        
        private string FullNameField;
        
        private int IdField;
        
        private byte[] ImgField;
        
        private string JobField;
        
        private string MobileField;
        
        private string PersonalNoField;
        
        private string PositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthDateStr
        {
            get
            {
                return this.BirthDateStrField;
            }
            set
            {
                this.BirthDateStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dep
        {
            get
            {
                return this.DepField;
            }
            set
            {
                this.DepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Img
        {
            get
            {
                return this.ImgField;
            }
            set
            {
                this.ImgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job
        {
            get
            {
                return this.JobField;
            }
            set
            {
                this.JobField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalNo
        {
            get
            {
                return this.PersonalNoField;
            }
            set
            {
                this.PersonalNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResult", Namespace="http://schemas.datacontract.org/2004/07/PMS.Models")]
    public partial class AuthenticationResult : object
    {
        
        private string FullNameField;
        
        private string IPPhoneField;
        
        private string LoginNameField;
        
        private string MessageField;
        
        private System.Collections.Generic.List<UserService.PermissionInfo> PermissionsField;
        
        private string PersonalNoField;
        
        private bool ResultField;
        
        private System.Collections.Generic.List<UserService.RoleInfo> RolesField;
        
        private System.Guid SessionIDField;
        
        private string SessionTokenField;
        
        private int UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPPhone
        {
            get
            {
                return this.IPPhoneField;
            }
            set
            {
                this.IPPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName
        {
            get
            {
                return this.LoginNameField;
            }
            set
            {
                this.LoginNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<UserService.PermissionInfo> Permissions
        {
            get
            {
                return this.PermissionsField;
            }
            set
            {
                this.PermissionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalNo
        {
            get
            {
                return this.PersonalNoField;
            }
            set
            {
                this.PersonalNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<UserService.RoleInfo> Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SessionID
        {
            get
            {
                return this.SessionIDField;
            }
            set
            {
                this.SessionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionToken
        {
            get
            {
                return this.SessionTokenField;
            }
            set
            {
                this.SessionTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermissionInfo", Namespace="http://schemas.datacontract.org/2004/07/PMS.Models")]
    public partial class PermissionInfo : object
    {
        
        private UserService.AppInfo AppInfoField;
        
        private string DescriptionField;
        
        private int IDField;
        
        private string KeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserService.AppInfo AppInfo
        {
            get
            {
                return this.AppInfoField;
            }
            set
            {
                this.AppInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleInfo", Namespace="http://schemas.datacontract.org/2004/07/PMS.Models")]
    public partial class RoleInfo : object
    {
        
        private UserService.AppInfo ApplicationField;
        
        private string DescriptionField;
        
        private int IDField;
        
        private string NameField;
        
        private System.Collections.Generic.List<UserService.PermissionInfo> PermissionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserService.AppInfo Application
        {
            get
            {
                return this.ApplicationField;
            }
            set
            {
                this.ApplicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<UserService.PermissionInfo> Permissions
        {
            get
            {
                return this.PermissionsField;
            }
            set
            {
                this.PermissionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppInfo", Namespace="http://schemas.datacontract.org/2004/07/PMS.Models")]
    public partial class AppInfo : object
    {
        
        private string DescriptionField;
        
        private System.Guid IDField;
        
        private string NameField;
        
        private System.Collections.Generic.List<UserService.RoleInfo> RolesField;
        
        private int TimeOutField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<UserService.RoleInfo> Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeOut
        {
            get
            {
                return this.TimeOutField;
            }
            set
            {
                this.TimeOutField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseInfo", Namespace="http://schemas.datacontract.org/2004/07/PMS.Models")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserService.UserVerificationInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserService.UserResponse))]
    public partial class BaseInfo : object
    {
        
        private string MessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserVerificationInfo", Namespace="http://schemas.datacontract.org/2004/07/PMS.Models")]
    public partial class UserVerificationInfo : UserService.BaseInfo
    {
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserResponse", Namespace="http://schemas.datacontract.org/2004/07/PMS.Models")]
    public partial class UserResponse : UserService.BaseInfo
    {
        
        private bool ActiveField;
        
        private System.Collections.Generic.List<string> RolesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResultPortal", Namespace="http://schemas.datacontract.org/2004/07/PMS.Models")]
    public partial class AuthenticationResultPortal : object
    {
        
        private string FirstNameField;
        
        private string FullNameField;
        
        private string LastNameField;
        
        private string LoginNameField;
        
        private string MessageField;
        
        private System.Collections.Generic.List<UserService.PermissionInfo> PermissionsField;
        
        private string PersonalNoField;
        
        private string PhoneNumberField;
        
        private bool ResultField;
        
        private System.Collections.Generic.List<UserService.RoleInfo> RolesField;
        
        private System.Guid SessionIDField;
        
        private string SessionTokenField;
        
        private int UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName
        {
            get
            {
                return this.LoginNameField;
            }
            set
            {
                this.LoginNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<UserService.PermissionInfo> Permissions
        {
            get
            {
                return this.PermissionsField;
            }
            set
            {
                this.PermissionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalNo
        {
            get
            {
                return this.PersonalNoField;
            }
            set
            {
                this.PersonalNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<UserService.RoleInfo> Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SessionID
        {
            get
            {
                return this.SessionIDField;
            }
            set
            {
                this.SessionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionToken
        {
            get
            {
                return this.SessionTokenField;
            }
            set
            {
                this.SessionTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.ISessionManager")]
    public interface ISessionManager
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ListBirthDays", ReplyAction="http://tempuri.org/ISessionManager/ListBirthDaysResponse")]
        System.Collections.Generic.List<UserService.AxWorkerInfo> ListBirthDays();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ListBirthDays", ReplyAction="http://tempuri.org/ISessionManager/ListBirthDaysResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UserService.AxWorkerInfo>> ListBirthDaysAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/Auth", ReplyAction="http://tempuri.org/ISessionManager/AuthResponse")]
        UserService.AuthenticationResult Auth(string personalNo, string password, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/Auth", ReplyAction="http://tempuri.org/ISessionManager/AuthResponse")]
        System.Threading.Tasks.Task<UserService.AuthenticationResult> AuthAsync(string personalNo, string password, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/Reg", ReplyAction="http://tempuri.org/ISessionManager/RegResponse")]
        UserService.BaseInfo Reg(string personalNo, string password, string repeatPassword, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/Reg", ReplyAction="http://tempuri.org/ISessionManager/RegResponse")]
        System.Threading.Tasks.Task<UserService.BaseInfo> RegAsync(string personalNo, string password, string repeatPassword, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/Verify", ReplyAction="http://tempuri.org/ISessionManager/VerifyResponse")]
        UserService.UserVerificationInfo Verify(string personalNo, string smsCode, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/Verify", ReplyAction="http://tempuri.org/ISessionManager/VerifyResponse")]
        System.Threading.Tasks.Task<UserService.UserVerificationInfo> VerifyAsync(string personalNo, string smsCode, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/SendPasswordReset", ReplyAction="http://tempuri.org/ISessionManager/SendPasswordResetResponse")]
        UserService.UserVerificationInfo SendPasswordReset(string personalNo, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/SendPasswordReset", ReplyAction="http://tempuri.org/ISessionManager/SendPasswordResetResponse")]
        System.Threading.Tasks.Task<UserService.UserVerificationInfo> SendPasswordResetAsync(string personalNo, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/VerifyPasswordReset", ReplyAction="http://tempuri.org/ISessionManager/VerifyPasswordResetResponse")]
        UserService.UserVerificationInfo VerifyPasswordReset(string personalNo, string smsCode, string password, string repeatPassword, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/VerifyPasswordReset", ReplyAction="http://tempuri.org/ISessionManager/VerifyPasswordResetResponse")]
        System.Threading.Tasks.Task<UserService.UserVerificationInfo> VerifyPasswordResetAsync(string personalNo, string smsCode, string password, string repeatPassword, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/Search", ReplyAction="http://tempuri.org/ISessionManager/SearchResponse")]
        System.Collections.Generic.List<UserService.AxWorkerInfo> Search(string searchKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/Search", ReplyAction="http://tempuri.org/ISessionManager/SearchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UserService.AxWorkerInfo>> SearchAsync(string searchKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/GetAxWorkerInfo", ReplyAction="http://tempuri.org/ISessionManager/GetAxWorkerInfoResponse")]
        UserService.AxWorkerInfo GetAxWorkerInfo(string personalNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/GetAxWorkerInfo", ReplyAction="http://tempuri.org/ISessionManager/GetAxWorkerInfoResponse")]
        System.Threading.Tasks.Task<UserService.AxWorkerInfo> GetAxWorkerInfoAsync(string personalNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/GetUserInfo", ReplyAction="http://tempuri.org/ISessionManager/GetUserInfoResponse")]
        UserService.UserResponse GetUserInfo(System.Guid applicationId, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/GetUserInfo", ReplyAction="http://tempuri.org/ISessionManager/GetUserInfoResponse")]
        System.Threading.Tasks.Task<UserService.UserResponse> GetUserInfoAsync(System.Guid applicationId, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/CreateLocalUserInfo", ReplyAction="http://tempuri.org/ISessionManager/CreateLocalUserInfoResponse")]
        bool CreateLocalUserInfo(string userName, string password, string personalNumber, string firstName, string lastName, string mail, System.Guid applicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/CreateLocalUserInfo", ReplyAction="http://tempuri.org/ISessionManager/CreateLocalUserInfoResponse")]
        System.Threading.Tasks.Task<bool> CreateLocalUserInfoAsync(string userName, string password, string personalNumber, string firstName, string lastName, string mail, System.Guid applicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/AuthByIdNumber", ReplyAction="http://tempuri.org/ISessionManager/AuthByIdNumberResponse")]
        UserService.AuthenticationResult AuthByIdNumber(System.Guid applicationId, string idNumber, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/AuthByIdNumber", ReplyAction="http://tempuri.org/ISessionManager/AuthByIdNumberResponse")]
        System.Threading.Tasks.Task<UserService.AuthenticationResult> AuthByIdNumberAsync(System.Guid applicationId, string idNumber, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/Authenticate", ReplyAction="http://tempuri.org/ISessionManager/AuthenticateResponse")]
        UserService.AuthenticationResult Authenticate(System.Guid applicationId, string userName, string password, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/Authenticate", ReplyAction="http://tempuri.org/ISessionManager/AuthenticateResponse")]
        System.Threading.Tasks.Task<UserService.AuthenticationResult> AuthenticateAsync(System.Guid applicationId, string userName, string password, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/AuthenticatePortal", ReplyAction="http://tempuri.org/ISessionManager/AuthenticatePortalResponse")]
        UserService.AuthenticationResultPortal AuthenticatePortal(System.Guid applicationId, string userName, string password, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/AuthenticatePortal", ReplyAction="http://tempuri.org/ISessionManager/AuthenticatePortalResponse")]
        System.Threading.Tasks.Task<UserService.AuthenticationResultPortal> AuthenticatePortalAsync(System.Guid applicationId, string userName, string password, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/InterAuthenticate", ReplyAction="http://tempuri.org/ISessionManager/InterAuthenticateResponse")]
        UserService.AuthenticationResult InterAuthenticate(System.Guid applicationId, string userName, string password, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/InterAuthenticate", ReplyAction="http://tempuri.org/ISessionManager/InterAuthenticateResponse")]
        System.Threading.Tasks.Task<UserService.AuthenticationResult> InterAuthenticateAsync(System.Guid applicationId, string userName, string password, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ValidateSession", ReplyAction="http://tempuri.org/ISessionManager/ValidateSessionResponse")]
        UserService.AuthenticationResult ValidateSession(System.Guid sessionID, string sessionToken, System.Guid applicationID, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ValidateSession", ReplyAction="http://tempuri.org/ISessionManager/ValidateSessionResponse")]
        System.Threading.Tasks.Task<UserService.AuthenticationResult> ValidateSessionAsync(System.Guid sessionID, string sessionToken, System.Guid applicationID, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ValidatePermission", ReplyAction="http://tempuri.org/ISessionManager/ValidatePermissionResponse")]
        void ValidatePermission(System.Guid sessionId, string sessionToken, string permissionKey, System.Guid applicationId, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ValidatePermission", ReplyAction="http://tempuri.org/ISessionManager/ValidatePermissionResponse")]
        System.Threading.Tasks.Task ValidatePermissionAsync(System.Guid sessionId, string sessionToken, string permissionKey, System.Guid applicationId, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ValidatePermissionWithValue", ReplyAction="http://tempuri.org/ISessionManager/ValidatePermissionWithValueResponse")]
        void ValidatePermissionWithValue(System.Guid sessionId, string sessionToken, string permissionKey, System.Guid applicationId, string methodName, string clientIP, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ValidatePermissionWithValue", ReplyAction="http://tempuri.org/ISessionManager/ValidatePermissionWithValueResponse")]
        System.Threading.Tasks.Task ValidatePermissionWithValueAsync(System.Guid sessionId, string sessionToken, string permissionKey, System.Guid applicationId, string methodName, string clientIP, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ValidateExternalSource", ReplyAction="http://tempuri.org/ISessionManager/ValidateExternalSourceResponse")]
        void ValidateExternalSource(System.Guid sourceId, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ValidateExternalSource", ReplyAction="http://tempuri.org/ISessionManager/ValidateExternalSourceResponse")]
        System.Threading.Tasks.Task ValidateExternalSourceAsync(System.Guid sourceId, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/GetCurrentUserRoles", ReplyAction="http://tempuri.org/ISessionManager/GetCurrentUserRolesResponse")]
        System.Collections.Generic.List<string> GetCurrentUserRoles(System.Guid sessionId, string sessionToken, System.Guid applicationId, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/GetCurrentUserRoles", ReplyAction="http://tempuri.org/ISessionManager/GetCurrentUserRolesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetCurrentUserRolesAsync(System.Guid sessionId, string sessionToken, System.Guid applicationId, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ResetUserName", ReplyAction="http://tempuri.org/ISessionManager/ResetUserNameResponse")]
        string ResetUserName(string personalNumber, string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ResetUserName", ReplyAction="http://tempuri.org/ISessionManager/ResetUserNameResponse")]
        System.Threading.Tasks.Task<string> ResetUserNameAsync(string personalNumber, string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ResetPassword", ReplyAction="http://tempuri.org/ISessionManager/ResetPasswordResponse")]
        bool ResetPassword(string personalNumber, string loginName, string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ResetPassword", ReplyAction="http://tempuri.org/ISessionManager/ResetPasswordResponse")]
        System.Threading.Tasks.Task<bool> ResetPasswordAsync(string personalNumber, string loginName, string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/SyncUser", ReplyAction="http://tempuri.org/ISessionManager/SyncUserResponse")]
        bool SyncUser(System.Guid sessionId, string domainLoginName, string personalNumber, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/SyncUser", ReplyAction="http://tempuri.org/ISessionManager/SyncUserResponse")]
        System.Threading.Tasks.Task<bool> SyncUserAsync(System.Guid sessionId, string domainLoginName, string personalNumber, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/CreateGWPortalUser", ReplyAction="http://tempuri.org/ISessionManager/CreateGWPortalUserResponse")]
        bool CreateGWPortalUser(string mail, string password, string personalNumber, string firstName, string lastName, string phone, string smsCode, System.Guid applicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/CreateGWPortalUser", ReplyAction="http://tempuri.org/ISessionManager/CreateGWPortalUserResponse")]
        System.Threading.Tasks.Task<bool> CreateGWPortalUserAsync(string mail, string password, string personalNumber, string firstName, string lastName, string phone, string smsCode, System.Guid applicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ResetGWPortalPassword", ReplyAction="http://tempuri.org/ISessionManager/ResetGWPortalPasswordResponse")]
        bool ResetGWPortalPassword(string mail, string phone, string smsCode, System.Guid applicationId, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ResetGWPortalPassword", ReplyAction="http://tempuri.org/ISessionManager/ResetGWPortalPasswordResponse")]
        System.Threading.Tasks.Task<bool> ResetGWPortalPasswordAsync(string mail, string phone, string smsCode, System.Guid applicationId, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/VerifyGWPortalPasswordReset", ReplyAction="http://tempuri.org/ISessionManager/VerifyGWPortalPasswordResetResponse")]
        bool VerifyGWPortalPasswordReset(string mail, string phone, string password, string smsCode, System.Guid applicationId, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/VerifyGWPortalPasswordReset", ReplyAction="http://tempuri.org/ISessionManager/VerifyGWPortalPasswordResetResponse")]
        System.Threading.Tasks.Task<bool> VerifyGWPortalPasswordResetAsync(string mail, string phone, string password, string smsCode, System.Guid applicationId, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/VerifyGWPortalUserSmsCode", ReplyAction="http://tempuri.org/ISessionManager/VerifyGWPortalUserSmsCodeResponse")]
        bool VerifyGWPortalUserSmsCode(string mail, string password, string personalNumber, string firstName, string lastName, string phone, string smsVerifiedCode, string mailCode, System.Guid applicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/VerifyGWPortalUserSmsCode", ReplyAction="http://tempuri.org/ISessionManager/VerifyGWPortalUserSmsCodeResponse")]
        System.Threading.Tasks.Task<bool> VerifyGWPortalUserSmsCodeAsync(string mail, string password, string personalNumber, string firstName, string lastName, string phone, string smsVerifiedCode, string mailCode, System.Guid applicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/CompleteGWPortalUserRegistration", ReplyAction="http://tempuri.org/ISessionManager/CompleteGWPortalUserRegistrationResponse")]
        bool CompleteGWPortalUserRegistration(string smsCode, string verifiedMailCode, System.Guid applicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/CompleteGWPortalUserRegistration", ReplyAction="http://tempuri.org/ISessionManager/CompleteGWPortalUserRegistrationResponse")]
        System.Threading.Tasks.Task<bool> CompleteGWPortalUserRegistrationAsync(string smsCode, string verifiedMailCode, System.Guid applicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/UpdatePortalProfile", ReplyAction="http://tempuri.org/ISessionManager/UpdatePortalProfileResponse")]
        bool UpdatePortalProfile(System.Guid applicationId, int userId, string firstName, string lastName, string personalNo, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/UpdatePortalProfile", ReplyAction="http://tempuri.org/ISessionManager/UpdatePortalProfileResponse")]
        System.Threading.Tasks.Task<bool> UpdatePortalProfileAsync(System.Guid applicationId, int userId, string firstName, string lastName, string personalNo, string methodName, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ChangeGWPortalPassword", ReplyAction="http://tempuri.org/ISessionManager/ChangeGWPortalPasswordResponse")]
        bool ChangeGWPortalPassword(int userId, string mail, string oldPassword, string newPassword, System.Guid applicationId, string clientIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManager/ChangeGWPortalPassword", ReplyAction="http://tempuri.org/ISessionManager/ChangeGWPortalPasswordResponse")]
        System.Threading.Tasks.Task<bool> ChangeGWPortalPasswordAsync(int userId, string mail, string oldPassword, string newPassword, System.Guid applicationId, string clientIP);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ISessionManagerChannel : UserService.ISessionManager, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SessionManagerClient : System.ServiceModel.ClientBase<UserService.ISessionManager>, UserService.ISessionManager
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SessionManagerClient() : 
                base(SessionManagerClient.GetDefaultBinding(), SessionManagerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISessionManager.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionManagerClient(EndpointConfiguration endpointConfiguration) : 
                base(SessionManagerClient.GetBindingForEndpoint(endpointConfiguration), SessionManagerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionManagerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SessionManagerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionManagerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SessionManagerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<UserService.AxWorkerInfo> ListBirthDays()
        {
            return base.Channel.ListBirthDays();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UserService.AxWorkerInfo>> ListBirthDaysAsync()
        {
            return base.Channel.ListBirthDaysAsync();
        }
        
        public UserService.AuthenticationResult Auth(string personalNo, string password, string clientIP)
        {
            return base.Channel.Auth(personalNo, password, clientIP);
        }
        
        public System.Threading.Tasks.Task<UserService.AuthenticationResult> AuthAsync(string personalNo, string password, string clientIP)
        {
            return base.Channel.AuthAsync(personalNo, password, clientIP);
        }
        
        public UserService.BaseInfo Reg(string personalNo, string password, string repeatPassword, string clientIP)
        {
            return base.Channel.Reg(personalNo, password, repeatPassword, clientIP);
        }
        
        public System.Threading.Tasks.Task<UserService.BaseInfo> RegAsync(string personalNo, string password, string repeatPassword, string clientIP)
        {
            return base.Channel.RegAsync(personalNo, password, repeatPassword, clientIP);
        }
        
        public UserService.UserVerificationInfo Verify(string personalNo, string smsCode, string clientIP)
        {
            return base.Channel.Verify(personalNo, smsCode, clientIP);
        }
        
        public System.Threading.Tasks.Task<UserService.UserVerificationInfo> VerifyAsync(string personalNo, string smsCode, string clientIP)
        {
            return base.Channel.VerifyAsync(personalNo, smsCode, clientIP);
        }
        
        public UserService.UserVerificationInfo SendPasswordReset(string personalNo, string clientIP)
        {
            return base.Channel.SendPasswordReset(personalNo, clientIP);
        }
        
        public System.Threading.Tasks.Task<UserService.UserVerificationInfo> SendPasswordResetAsync(string personalNo, string clientIP)
        {
            return base.Channel.SendPasswordResetAsync(personalNo, clientIP);
        }
        
        public UserService.UserVerificationInfo VerifyPasswordReset(string personalNo, string smsCode, string password, string repeatPassword, string clientIP)
        {
            return base.Channel.VerifyPasswordReset(personalNo, smsCode, password, repeatPassword, clientIP);
        }
        
        public System.Threading.Tasks.Task<UserService.UserVerificationInfo> VerifyPasswordResetAsync(string personalNo, string smsCode, string password, string repeatPassword, string clientIP)
        {
            return base.Channel.VerifyPasswordResetAsync(personalNo, smsCode, password, repeatPassword, clientIP);
        }
        
        public System.Collections.Generic.List<UserService.AxWorkerInfo> Search(string searchKey)
        {
            return base.Channel.Search(searchKey);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UserService.AxWorkerInfo>> SearchAsync(string searchKey)
        {
            return base.Channel.SearchAsync(searchKey);
        }
        
        public UserService.AxWorkerInfo GetAxWorkerInfo(string personalNo)
        {
            return base.Channel.GetAxWorkerInfo(personalNo);
        }
        
        public System.Threading.Tasks.Task<UserService.AxWorkerInfo> GetAxWorkerInfoAsync(string personalNo)
        {
            return base.Channel.GetAxWorkerInfoAsync(personalNo);
        }
        
        public UserService.UserResponse GetUserInfo(System.Guid applicationId, string userName)
        {
            return base.Channel.GetUserInfo(applicationId, userName);
        }
        
        public System.Threading.Tasks.Task<UserService.UserResponse> GetUserInfoAsync(System.Guid applicationId, string userName)
        {
            return base.Channel.GetUserInfoAsync(applicationId, userName);
        }
        
        public bool CreateLocalUserInfo(string userName, string password, string personalNumber, string firstName, string lastName, string mail, System.Guid applicationId)
        {
            return base.Channel.CreateLocalUserInfo(userName, password, personalNumber, firstName, lastName, mail, applicationId);
        }
        
        public System.Threading.Tasks.Task<bool> CreateLocalUserInfoAsync(string userName, string password, string personalNumber, string firstName, string lastName, string mail, System.Guid applicationId)
        {
            return base.Channel.CreateLocalUserInfoAsync(userName, password, personalNumber, firstName, lastName, mail, applicationId);
        }
        
        public UserService.AuthenticationResult AuthByIdNumber(System.Guid applicationId, string idNumber, string methodName, string clientIP)
        {
            return base.Channel.AuthByIdNumber(applicationId, idNumber, methodName, clientIP);
        }
        
        public System.Threading.Tasks.Task<UserService.AuthenticationResult> AuthByIdNumberAsync(System.Guid applicationId, string idNumber, string methodName, string clientIP)
        {
            return base.Channel.AuthByIdNumberAsync(applicationId, idNumber, methodName, clientIP);
        }
        
        public UserService.AuthenticationResult Authenticate(System.Guid applicationId, string userName, string password, string methodName, string clientIP)
        {
            return base.Channel.Authenticate(applicationId, userName, password, methodName, clientIP);
        }
        
        public System.Threading.Tasks.Task<UserService.AuthenticationResult> AuthenticateAsync(System.Guid applicationId, string userName, string password, string methodName, string clientIP)
        {
            return base.Channel.AuthenticateAsync(applicationId, userName, password, methodName, clientIP);
        }
        
        public UserService.AuthenticationResultPortal AuthenticatePortal(System.Guid applicationId, string userName, string password, string methodName, string clientIP)
        {
            return base.Channel.AuthenticatePortal(applicationId, userName, password, methodName, clientIP);
        }
        
        public System.Threading.Tasks.Task<UserService.AuthenticationResultPortal> AuthenticatePortalAsync(System.Guid applicationId, string userName, string password, string methodName, string clientIP)
        {
            return base.Channel.AuthenticatePortalAsync(applicationId, userName, password, methodName, clientIP);
        }
        
        public UserService.AuthenticationResult InterAuthenticate(System.Guid applicationId, string userName, string password, string methodName, string clientIP)
        {
            return base.Channel.InterAuthenticate(applicationId, userName, password, methodName, clientIP);
        }
        
        public System.Threading.Tasks.Task<UserService.AuthenticationResult> InterAuthenticateAsync(System.Guid applicationId, string userName, string password, string methodName, string clientIP)
        {
            return base.Channel.InterAuthenticateAsync(applicationId, userName, password, methodName, clientIP);
        }
        
        public UserService.AuthenticationResult ValidateSession(System.Guid sessionID, string sessionToken, System.Guid applicationID, string methodName, string clientIP)
        {
            return base.Channel.ValidateSession(sessionID, sessionToken, applicationID, methodName, clientIP);
        }
        
        public System.Threading.Tasks.Task<UserService.AuthenticationResult> ValidateSessionAsync(System.Guid sessionID, string sessionToken, System.Guid applicationID, string methodName, string clientIP)
        {
            return base.Channel.ValidateSessionAsync(sessionID, sessionToken, applicationID, methodName, clientIP);
        }
        
        public void ValidatePermission(System.Guid sessionId, string sessionToken, string permissionKey, System.Guid applicationId, string methodName, string clientIP)
        {
            base.Channel.ValidatePermission(sessionId, sessionToken, permissionKey, applicationId, methodName, clientIP);
        }
        
        public System.Threading.Tasks.Task ValidatePermissionAsync(System.Guid sessionId, string sessionToken, string permissionKey, System.Guid applicationId, string methodName, string clientIP)
        {
            return base.Channel.ValidatePermissionAsync(sessionId, sessionToken, permissionKey, applicationId, methodName, clientIP);
        }
        
        public void ValidatePermissionWithValue(System.Guid sessionId, string sessionToken, string permissionKey, System.Guid applicationId, string methodName, string clientIP, string value)
        {
            base.Channel.ValidatePermissionWithValue(sessionId, sessionToken, permissionKey, applicationId, methodName, clientIP, value);
        }
        
        public System.Threading.Tasks.Task ValidatePermissionWithValueAsync(System.Guid sessionId, string sessionToken, string permissionKey, System.Guid applicationId, string methodName, string clientIP, string value)
        {
            return base.Channel.ValidatePermissionWithValueAsync(sessionId, sessionToken, permissionKey, applicationId, methodName, clientIP, value);
        }
        
        public void ValidateExternalSource(System.Guid sourceId, string methodName, string clientIP)
        {
            base.Channel.ValidateExternalSource(sourceId, methodName, clientIP);
        }
        
        public System.Threading.Tasks.Task ValidateExternalSourceAsync(System.Guid sourceId, string methodName, string clientIP)
        {
            return base.Channel.ValidateExternalSourceAsync(sourceId, methodName, clientIP);
        }
        
        public System.Collections.Generic.List<string> GetCurrentUserRoles(System.Guid sessionId, string sessionToken, System.Guid applicationId, string methodName, string clientIP)
        {
            return base.Channel.GetCurrentUserRoles(sessionId, sessionToken, applicationId, methodName, clientIP);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetCurrentUserRolesAsync(System.Guid sessionId, string sessionToken, System.Guid applicationId, string methodName, string clientIP)
        {
            return base.Channel.GetCurrentUserRolesAsync(sessionId, sessionToken, applicationId, methodName, clientIP);
        }
        
        public string ResetUserName(string personalNumber, string firstName, string lastName)
        {
            return base.Channel.ResetUserName(personalNumber, firstName, lastName);
        }
        
        public System.Threading.Tasks.Task<string> ResetUserNameAsync(string personalNumber, string firstName, string lastName)
        {
            return base.Channel.ResetUserNameAsync(personalNumber, firstName, lastName);
        }
        
        public bool ResetPassword(string personalNumber, string loginName, string mail)
        {
            return base.Channel.ResetPassword(personalNumber, loginName, mail);
        }
        
        public System.Threading.Tasks.Task<bool> ResetPasswordAsync(string personalNumber, string loginName, string mail)
        {
            return base.Channel.ResetPasswordAsync(personalNumber, loginName, mail);
        }
        
        public bool SyncUser(System.Guid sessionId, string domainLoginName, string personalNumber, string methodName, string clientIP)
        {
            return base.Channel.SyncUser(sessionId, domainLoginName, personalNumber, methodName, clientIP);
        }
        
        public System.Threading.Tasks.Task<bool> SyncUserAsync(System.Guid sessionId, string domainLoginName, string personalNumber, string methodName, string clientIP)
        {
            return base.Channel.SyncUserAsync(sessionId, domainLoginName, personalNumber, methodName, clientIP);
        }
        
        public bool CreateGWPortalUser(string mail, string password, string personalNumber, string firstName, string lastName, string phone, string smsCode, System.Guid applicationId)
        {
            return base.Channel.CreateGWPortalUser(mail, password, personalNumber, firstName, lastName, phone, smsCode, applicationId);
        }
        
        public System.Threading.Tasks.Task<bool> CreateGWPortalUserAsync(string mail, string password, string personalNumber, string firstName, string lastName, string phone, string smsCode, System.Guid applicationId)
        {
            return base.Channel.CreateGWPortalUserAsync(mail, password, personalNumber, firstName, lastName, phone, smsCode, applicationId);
        }
        
        public bool ResetGWPortalPassword(string mail, string phone, string smsCode, System.Guid applicationId, string clientIP)
        {
            return base.Channel.ResetGWPortalPassword(mail, phone, smsCode, applicationId, clientIP);
        }
        
        public System.Threading.Tasks.Task<bool> ResetGWPortalPasswordAsync(string mail, string phone, string smsCode, System.Guid applicationId, string clientIP)
        {
            return base.Channel.ResetGWPortalPasswordAsync(mail, phone, smsCode, applicationId, clientIP);
        }
        
        public bool VerifyGWPortalPasswordReset(string mail, string phone, string password, string smsCode, System.Guid applicationId, string clientIP)
        {
            return base.Channel.VerifyGWPortalPasswordReset(mail, phone, password, smsCode, applicationId, clientIP);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyGWPortalPasswordResetAsync(string mail, string phone, string password, string smsCode, System.Guid applicationId, string clientIP)
        {
            return base.Channel.VerifyGWPortalPasswordResetAsync(mail, phone, password, smsCode, applicationId, clientIP);
        }
        
        public bool VerifyGWPortalUserSmsCode(string mail, string password, string personalNumber, string firstName, string lastName, string phone, string smsVerifiedCode, string mailCode, System.Guid applicationId)
        {
            return base.Channel.VerifyGWPortalUserSmsCode(mail, password, personalNumber, firstName, lastName, phone, smsVerifiedCode, mailCode, applicationId);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyGWPortalUserSmsCodeAsync(string mail, string password, string personalNumber, string firstName, string lastName, string phone, string smsVerifiedCode, string mailCode, System.Guid applicationId)
        {
            return base.Channel.VerifyGWPortalUserSmsCodeAsync(mail, password, personalNumber, firstName, lastName, phone, smsVerifiedCode, mailCode, applicationId);
        }
        
        public bool CompleteGWPortalUserRegistration(string smsCode, string verifiedMailCode, System.Guid applicationId)
        {
            return base.Channel.CompleteGWPortalUserRegistration(smsCode, verifiedMailCode, applicationId);
        }
        
        public System.Threading.Tasks.Task<bool> CompleteGWPortalUserRegistrationAsync(string smsCode, string verifiedMailCode, System.Guid applicationId)
        {
            return base.Channel.CompleteGWPortalUserRegistrationAsync(smsCode, verifiedMailCode, applicationId);
        }
        
        public bool UpdatePortalProfile(System.Guid applicationId, int userId, string firstName, string lastName, string personalNo, string methodName, string clientIP)
        {
            return base.Channel.UpdatePortalProfile(applicationId, userId, firstName, lastName, personalNo, methodName, clientIP);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePortalProfileAsync(System.Guid applicationId, int userId, string firstName, string lastName, string personalNo, string methodName, string clientIP)
        {
            return base.Channel.UpdatePortalProfileAsync(applicationId, userId, firstName, lastName, personalNo, methodName, clientIP);
        }
        
        public bool ChangeGWPortalPassword(int userId, string mail, string oldPassword, string newPassword, System.Guid applicationId, string clientIP)
        {
            return base.Channel.ChangeGWPortalPassword(userId, mail, oldPassword, newPassword, applicationId, clientIP);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeGWPortalPasswordAsync(int userId, string mail, string oldPassword, string newPassword, System.Guid applicationId, string clientIP)
        {
            return base.Channel.ChangeGWPortalPasswordAsync(userId, mail, oldPassword, newPassword, applicationId, clientIP);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISessionManager))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISessionManager))
            {
                return new System.ServiceModel.EndpointAddress("http://pms.gwp.ge/Service/SessionManager.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SessionManagerClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISessionManager);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SessionManagerClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISessionManager);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISessionManager,
        }
    }
}
